var sqlite3 = require('sqlite3').verbose();
var db = new sqlite3.Database('data/segmentacion.db');

/** Create table TIER **/
var sqlString = "CREATE TABLE IF NOT EXISTS TIER(NUMERO INTEGER PRIMARY KEY, PUNTOS_T REAL);";
db.run(sqlString);
/** Create table Grupo **/
sqlString = "CREATE TABLE IF NOT EXISTS GRUPO(ID INTEGER PRIMARY KEY, NOMBRE TEXT, DESCRIPCION TEXT );";
db.run(sqlString);
/** Create table Usuario **/
sqlString = "CREATE TABLE IF NOT EXISTS USUARIO(ID TEXT PRIMARY KEY, NOMBRE  TEXT, EXPERIENCIA REAL, TIER_ACTUAL INTEGER,"
+"PUNTOS REAL, TARJETA TEXT, FOREIGN KEY(TIER_ACTUAL) REFERENCES TIER(NUMERO) );";
db.run(sqlString);
/** Create table Reto **/
sqlString = "CREATE TABLE IF NOT EXISTS RETO(ID INTEGER PRIMARY KEY, NOMBRE TEXT, DESCRIPCION TEXT, TIPO INTEGER,"
+ "NUMERO_TIPO INTEGER, PUNTOS REAL, TIER_ASOCIADO INTEGER, GRUPO_ASOCIADO INTEGER,"
+ " FOREIGN KEY (TIER_ASOCIADO) REFERENCES TIER(NUMERO), FOREIGN KEY (GRUPO_ASOCIADO) REFERENCES GRUPO(ID) );";
db.run(sqlString);
/** Create table RetoUsuario **/
sqlString = "CREATE TABLE IF NOT EXISTS RETOS_USUARIO( ID_RETO INTEGER, ID_USUARIO INTEGER, STATUS BOOLEAN,"
+ "PRIMARY KEY (ID_RETO, ID_USUARIO), FOREIGN KEY (ID_RETO) REFERENCES RETO(ID), FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID) );";
db.run(sqlString);
/** Create table Premio **/
sqlString = "CREATE TABLE PREMIO(ID INTEGER PRIMARY KEY,NOMBRE TEXT,DESCRIPCION TEXT,"
+"TIER_ASOCIADO INTEGER,GRUPO_ASOCIADO INTEGER, IMAGEN TEXT,FOREIGN KEY (TIER_ASOCIADO) REFERENCES TIER(NUMERO),"
+"FOREIGN KEY (GRUPO_ASOCIADO) REFERENCES GRUPO(ID));";
db.run(sqlString);
/** Create table Premio_Usuario  **/
sqlString = "CREATE TABLE PREMIO_USUARIO(ID_USUARIO INTEGER,ID_PREMIO INTEGER,REDIMIDO BOOLEAN,"
+"PRIMARY KEY (ID_PREMIO, ID_USUARIO),FOREIGN KEY (ID_PREMIO) REFERENCES PREMIO(ID),"
+"FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID));";
db.run(sqlString);
